stages:
  - build
  - test
  - deploy

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository
    - todo-list-front/node_modules/

build-backend:
  stage: build
  image: maven:3.8-openjdk-17
  script:
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - todolist-api-backend/target/*.jar

build-frontend:
  stage: build
  image: node:20
  script:
    - cd todo-list-front
    - npm install
    - npm run build
  artifacts:
    paths:
      - todo-list-front/dist/

test-backend:
  stage: test
  image: maven:3.8-openjdk-17
  script:
    - mvn test

test-frontend:
  stage: test
  image: node:20
  script:
    - cd todo-list-front
    - npm install
    - npm run test

deploy:
  stage: deploy
  script:
    - echo "Deploy to master"
  only:
    - master