services:
  postgres:
    container_name: postgres-sql-todolist
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: test_db
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-todolist-app
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

  networks:
    spring-demo:
      driver: bridge
  volumes:
    postgres:
      driver: local