spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todolist-app-dev
    username: username
    password: password
    driver-class-name: org.postgresql.Driver

  mail:
    host: localhost
    port: 1025
    username: dev
    password: dev

application:
  keycloak:
    resource: todolist-app-dev
    credentials:
      secret: RuCkwc6xqYt2UxYeKYKVVb5dp6HwmFXK

  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account

server:
  port: 8088