spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/todolist-app
          jwk-set-uri: http://localhost:8180/realms/todolist-app/protocol/openid-connect/certs

  mail:
    properties:
      mail:
        smtp:
          trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

#application:
#  keycloak:
#   realm: todolist-app
#    auth-server-url: http://localhost:8180

server:
  servlet:
    context-path: /api/v1